# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release upload

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml && mvn -B package --file Ree6-Installer/pom.xml
    - name: Copy Artifacts
      run: mkdir staging && cp target/*.jar staging && cp Ree6-Installer/target/*.jar staging
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Ree6-all
        path: staging
    - name: Upload to Pterodactyl
      uses: rexlmanu/pterodactyl-upload-action@v2.1
      with:
        panel-host: ${{ secrets.PANEL_HOST }}
        api-key: ${{ secrets.API_KEY }}
        server-id: "671f9a45"
          #   server-ids: |
          #     5f095019
          #     7f095019
        source: "staging/*.jar"
          #   sources: |
          #     hello.txt
          #     hello2.txt
        target: "./"
          # If you want to restart the servers after successful upload
        restart: true
          # If you want to decompress the files after successful upload
          # decompress-target: true
